spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:8080"
      client:
        registration:
          client-app:
            provider: spring
            client-id: frontend-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8001/authorized"
            scope:
            - openid
            - profile
            - read
            - write
            client-name: client-app
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:8080"